"""Added course and photo_url to Student

Revision ID: 138897fdd838
Revises: 
Create Date: 2025-05-04 18:04:34.689613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138897fdd838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('course')

    # ### end Alembic commands ###
